[build]
publish = "public"
command = "hugo --gc --minify -b ${URL}"

[build.environment]
HUGO_VERSION = "0.147.7"


[[redirects]]
  from = "https://hextra-ai-insight-daily.netlify.app/*"
  to = "https://ai.hubtoday.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://main--hextra-ai-insight-daily.netlify.app/*"
  to = "https://ai.hubtoday.app/:splat"
  status = 301
  force = true
